sudo: required
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
addons:
  apt:
    packages:
    - g++-4.9
    - libncursesw5-dev
    - libncursesw5-dev
    - liblua5.1-0-dev
    - pkg-config
    - libpcre3-dev
    - libgmime-2.6-dev
    - libmagic-dev
env:
    - LUA_VERSION=5.1
language: cpp
compiler:
  - g++
script: make

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libncursesw5-dev liblua5.1-0-dev pkg-config libpcre3-dev libgmime-2.6-dev
